# Generated by Django 4.2.16 on 2025-12-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='social_provider',
            field=models.CharField(blank=True, choices=[('', '일반 가입'), ('kakao', '카카오'), ('naver', '네이버'), ('google', '구글')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '이 이메일 주소는 이미 사용 중입니다.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('social_provider__gt', '')), fields=('social_provider', 'social_id'), name='unique_social_account'),
        ),
    ]
