# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_review_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='website_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
