# Generated by Django 4.2.16 on 2025-11-12 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_review_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '검토중'), ('approved', '승인됨'), ('rejected', '거절됨'), ('cancelled', '취소됨'), ('completed', '완료')], default='pending', max_length=20)),
                ('booth_type', models.CharField(choices=[('food', '음식 부스'), ('goods', '굿즈 판매'), ('experience', '체험 부스'), ('promotion', '홍보 부스')], max_length=20, verbose_name='부스 종류')),
                ('booth_size', models.CharField(choices=[('3x3', '3x3m (기본형)'), ('6x3', '6x3m (대형)'), ('custom', '맞춤형')], default='3x3', max_length=10, verbose_name='부스 크기')),
                ('products', models.TextField(help_text='예: 김밥, 떡볶이, 음료', verbose_name='판매/전시 품목')),
                ('price_range', models.CharField(blank=True, help_text='예: 3,000원 ~ 8,000원', max_length=100, verbose_name='가격대')),
                ('brand_intro', models.TextField(help_text='이 축제에 지원하는 이유 및 브랜드 소개', verbose_name='브랜드 소개')),
                ('brand_images', models.JSONField(blank=True, default=list, help_text='지원서에 첨부할 브랜드 이미지 URL 리스트')),
                ('has_experience', models.BooleanField(default=False, verbose_name='이전 축제 참여 경험 있음')),
                ('previous_festivals', models.TextField(blank=True, verbose_name='이전 참여 축제 목록')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='포트폴리오 URL')),
                ('special_requests', models.TextField(blank=True, help_text='예: 냉장고 필요, 전기 콘센트 2개 필요', verbose_name='추가 요청사항')),
                ('organizer_message', models.TextField(blank=True, verbose_name='주최자 메시지')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='거절 사유')),
                ('participation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='참가비')),
                ('payment_status', models.CharField(choices=[('unpaid', '미결제'), ('paid', '결제완료'), ('refunded', '환불완료')], default='unpaid', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booth_location', models.CharField(blank=True, help_text='예: A-12', max_length=50, verbose_name='부스 위치')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='지원일')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='events.event')),
            ],
            options={
                'verbose_name': '축제 지원서',
                'verbose_name_plural': '축제 지원서 목록',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='상호명')),
                ('business_number', models.CharField(max_length=50, unique=True, verbose_name='사업자등록번호')),
                ('representative_name', models.CharField(max_length=100, verbose_name='대표자명')),
                ('business_type', models.CharField(max_length=100, verbose_name='업종')),
                ('address', models.TextField(verbose_name='사업장 주소')),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(max_length=20, verbose_name='대표 연락처')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('business_certificate', models.URLField(blank=True, verbose_name='사업자등록증 이미지')),
                ('brand_name', models.CharField(max_length=200, verbose_name='브랜드명')),
                ('brand_logo', models.URLField(blank=True, verbose_name='브랜드 로고')),
                ('brand_intro', models.TextField(help_text='일반 유저에게 공개되는 소개글', verbose_name='브랜드 소개')),
                ('products', models.TextField(help_text='판매하는 제품 목록', verbose_name='대표 제품/메뉴')),
                ('sns_links', models.JSONField(blank=True, default=dict, help_text='{"instagram": "@username", "facebook": "...", "youtube": "..."}')),
                ('website', models.URLField(blank=True, verbose_name='공식 웹사이트')),
                ('portfolio_images', models.JSONField(blank=True, default=list, help_text='제품/메뉴 사진 URL 리스트')),
                ('festival_images', models.JSONField(blank=True, default=list, help_text='이전 축제 참여 사진 URL 리스트')),
                ('verified', models.BooleanField(default=False, verbose_name='사업자 인증 완료')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='인증 완료 일시')),
                ('total_applications', models.IntegerField(default=0, verbose_name='총 지원 횟수')),
                ('total_approvals', models.IntegerField(default=0, verbose_name='총 승인 횟수')),
                ('average_rating', models.FloatField(default=0, verbose_name='평균 평점')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사업자',
                'verbose_name_plural': '사업자 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('direct', '1:1 메시지'), ('announcement', '전체 공지')], default='direct', max_length=20)),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='파일 URL 리스트')),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='partners.application')),
                ('receiver', models.ForeignKey(blank=True, help_text='전체 공지인 경우 null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='partners.partner'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('partner', 'event')},
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_count', models.IntegerField(default=0, help_text='주최측 제공 데이터', verbose_name='방문객 수')),
                ('estimated_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='예상 판매액')),
                ('average_rating', models.FloatField(default=0, verbose_name='평균 평점')),
                ('review_count', models.IntegerField(default=0, verbose_name='리뷰 개수')),
                ('hourly_visitors', models.JSONField(blank=True, default=dict, help_text='{"10": 120, "11": 250, ...}')),
                ('top_products', models.JSONField(blank=True, default=list, help_text='[{"name": "참치김밥", "clicks": 485, "avg_time": 15}, ...]')),
                ('positive_keywords', models.JSONField(blank=True, default=list, help_text='긍정 키워드 및 빈도')),
                ('negative_keywords', models.JSONField(blank=True, default=list, help_text='부정 키워드 및 빈도')),
                ('sentiment_score', models.FloatField(default=0, help_text='0-100 (높을수록 긍정적)', verbose_name='감성 점수')),
                ('previous_event_comparison', models.JSONField(blank=True, default=dict, help_text='이전 축제와 비교 데이터')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='partners.application')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_analytics', to='events.event')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='partners.partner')),
            ],
            options={
                'verbose_name': '성과 데이터',
                'verbose_name_plural': '성과 데이터 목록',
                'unique_together': {('partner', 'event')},
            },
        ),
    ]
