# Generated by Django 4.2.16 on 2025-11-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('certificate', '사업자등록증'), ('logo', '브랜드 로고'), ('portfolio', '포트폴리오'), ('product', '제품 사진'), ('festival', '축제 참여 사진'), ('other', '기타')], max_length=20, verbose_name='이미지 종류')),
                ('image', models.ImageField(upload_to='partners/%Y/%m/%d/', verbose_name='이미지 파일')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_size', models.IntegerField(verbose_name='파일 크기 (bytes)')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partners.partner')),
            ],
            options={
                'verbose_name': '이미지 업로드',
                'verbose_name_plural': '이미지 업로드 목록',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
