# Generated by Django 4.2.16 on 2025-11-12 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0002_imageupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_submitted', '지원서 제출'), ('application_approved', '지원서 승인'), ('application_rejected', '지원서 거절'), ('message_received', '새 메시지'), ('event_reminder', '이벤트 알림'), ('payment_required', '결제 필요'), ('booth_assigned', '부스 배정'), ('analytics_ready', '성과 데이터 준비'), ('system', '시스템 알림')], max_length=30, verbose_name='알림 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지')),
                ('link', models.URLField(blank=True, help_text='클릭 시 이동할 URL', verbose_name='연결 링크')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='추가 메타데이터')),
                ('read', models.BooleanField(default=False, verbose_name='읽음')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='partners.application', verbose_name='관련 지원서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='partners_no_user_id_eb9cf3_idx')],
            },
        ),
    ]
