# Generated by Django 4.2.16 on 2025-11-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_review_bookmark'),
        ('partners', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, help_text='북마크 메모 (선택)', verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='북마크 일시')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='events.event', verbose_name='축제')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='partners.partner', verbose_name='사업자')),
            ],
            options={
                'verbose_name': '축제 북마크',
                'verbose_name_plural': '축제 북마크 목록',
                'ordering': ['-created_at'],
                'unique_together': {('partner', 'event')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_data', models.JSONField(default=dict, help_text='작성 중인 지원서 데이터', verbose_name='임시저장 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_drafts', to='events.event', verbose_name='축제')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='partners.partner', verbose_name='사업자')),
            ],
            options={
                'verbose_name': '임시저장 지원서',
                'verbose_name_plural': '임시저장 지원서 목록',
                'ordering': ['-updated_at'],
                'unique_together': {('partner', 'event')},
            },
        ),
    ]
